buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven { url = "https://maven.minecraftforge.net/" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.0"
group = "com.darkdims"
archivesBaseName = "DarkDims"

sourceCompatibility = targetCompatibility = '1.8'
compileJava.options.encoding = 'UTF-8'

minecraft {
    version = "1.12.2-14.23.5.2860"
    runDir = "run"
    mappings = "stable_39"
}
